### ISSUE TITLE
[PHP] sio1/sio2

### ISSUE THREAD

**Issue by ornech** [ornech/gestion_stage#100]
1) Faire une fonction PHP qui détermine si un utilisateur est en 1ere, 2ème année, un ancien étudiant ou un professeur 
2) Déterminer le meilleur emplacement afin qu'elle soit accessible partout

**Comment by Logan-Gaillard** [comment]
Pour cette issue, nous avons plusieurs possibilité :

1) 
On ajoute une colonne dans la table user de la DB. 
(Mais personnellement je trouve que ça ne servirai à rien)

2)
On peut l'ajouter dans root.php pour avoir directement une variable par exemple $anneeLycee

3)
Sinon au lieu de faire ce traitement à chaque fois que la page est chargé, nous pouvons le faire qu'une seul fois dans login.php et le résultat et mit dans la session.


De toute façon il faudra que je modifie Profil.php pour avoir une fonction qui récupère également l'année de promotion, qu'il la compare avec la date actuelle et qui nous renvoie un résultat. Et cela fonctionnera pour nous utilisateur qui est connecté et pour les autres.

Personnellement, je trouve que la solution n°3 plus correcte et vous ?
