### ISSUE TITLE
[FIX] page=stage_sio1

### ISSUE THREAD

**Issue by ornech** [ornech/gestion_stage#150]
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/gestion_stage/vues/navbar_prof.php:57) in /var/www/html/gestion_stage/model/Stage.php on line 56

**Comment by Logan-Gaillard** [comment]
Alors j'ai eu également cette erreur, c'est encore à cause de la vue qui est corrompue que ça effectue cela.

Mais cette erreur est tout de même a regardé car le header qui redirige sur la vue de l'erreur doit être bloqué par un var_dump() ou un echo ou bien un autre header.

**Comment by ornech** [comment]
FIX, pd de requête sur une colonne qui n'existait pas
