### ISSUE TITLE
[LOG] Lister les actions utilisateur

### ISSUE THREAD

**Issue by ornech** [ornech/gestion_stage#244]
Faire une fonction qui enregistre une action dont on souhaite conserver la trace. Typiquement la modification d'une données dans la base de données  (qui, quand et ancienne valeur, nouvelle valeur).

Cette fonction devra facilement être insérée dans une méthode d'un modèle par exemple s'il s'agit d'un update ou d'un insert SQL.

**Comment by Logan-Gaillard** [comment]
Il me reste la modification de l'entreprise et de faire en sorte pour Contact de ne plus faire addLog sur le modèle mais sur le contrôleur. (Car plus sûre)
