### ISSUE TITLE
[CONTACT] Ajout

### ISSUE THREAD

**Issue by ornech** [ornech/gestion_stage#314]
Imposer la validation d'un professeur après l'ajout d'un contact par un étudiant.
a) Le contact ajouté ne doit pas apparaitre tant qu'il n'a pas été validé par le professeur
b) modification de la DB, ajout d'un champ contact_valide
c) Ce champ est à 0 par défault
d) Ajouter un menu dans le navbar "Opérations à valider" -> Tableau de toutes les validations en attente de tous les étudiants (étudiant, type de demanand, date, tuteur de l'élève)
e) Ajouter une box dans la page d'acceuil qui rassembe les actions à valider pour un professeur

**Comment by Logan-Gaillard** [comment]
Dois-je faire également dans la vue opération à valider un bouton qui permet de refuser le contact et qui le supprime ?

**Comment by Logan-Gaillard** [comment]
Je me posait également la question: est-ce qu'il y aura autre chose que les nouveaux contacts à valider.
Si oui, serait-il pas mieux de faire une nouvelle table, ou bien une vue qui vérifie sur toutes que l'on choisi à pas un ***_valide à 0.

**Comment by patricedenis** [comment]
Il pourrait être intéressant en effet de vérifier les adresses ou les champs entrés pour les coordonnées des entreprises.
En effet le but est de pouvoir vérifier que n'importe quoi n'est pas entré dans la BD.

**Comment by Logan-Gaillard** [comment]
Je viens de faire une vue "vue_operations" à laquelle des infos seront stocké ici lorsque contact_valide est à 0
Et avec des UNION, je mettrait au fur et à mesure les autres table qui auront besoin d'être validé par un prof avant d'être visible.
![image](https://github.com/ornech/gestion_stage/assets/35261972/7114ed7c-bf5d-49e9-84bd-bf210c7f74c9)

**Comment by Logan-Gaillard** [comment]
Je vais faire la box dans une autre issue.
