### ISSUE TITLE
[LOGGIN] 3 - RGPD

### ISSUE THREAD

**Issue by ornech** [ornech/gestion_stage#320]
A) Faire la vue vue_cgu.php
B) Faire le controlleur
C) Modifier le modèle, ajouter la méthode qui va bien

## La vue:
1) détecter si dateFirstConn est NULL
2)  si NULL Afficher une fenêtre avec un formulaire contenant
 a) un texte avec  scrollbar (les CGU)
 b) un case à cochez "J'accepte"
 c) un bouton valider
3) Dans le backend, insérer NOW() dans dateFirstConn si les CGU ont été accepté. Ne pas laisser d'autre choix

**Comment by Logan-Gaillard** [comment]
![image](https://github.com/ornech/gestion_stage/assets/35261972/6a36e23a-4b53-4b3d-a8ee-7e5e59b94442)

**Comment by Logan-Gaillard** [comment]
Et tout en bas j'ai mit un petit texte bleu qui redirige vers la page des CGU : 
![image](https://github.com/ornech/gestion_stage/assets/35261972/14e65517-73e2-4d1a-a27f-d86cab32eca9)

**Comment by Logan-Gaillard** [comment]
A fermer si validé par le professeur
