### ISSUE TITLE
[VUE] formulaire création de profil

### ISSUE THREAD

**Issue by ornech** [ornech/gestion_stage#37]
Modification du code HTML pour intégrer Bootstrap

**Comment by ManRiick** [comment]
Rebonjour Monsieur Ornech. Dans la création de profil est-il possible d'ajouter une case à cocher pour les mots de passes?
[ ] Mdp par défaut (achanger)
pour pas écrire 2 fois achanger, et quand on le coche ca mets achanger dans mdp et confirmation de mdp?
et si on coche pas - on écris une autre chose que 'achanger'

**Comment by Logan-Gaillard** [comment]
Petit commentaire d'avancement de la page vue_profil_create_user : 

Je viens de lire la documentation et d'expérimenter Bootstrap, maintenant je me penche sur le design, j'ai commencé à faire ceci 
![image](https://github.com/ornech/gestion_stage/assets/35261972/a8153479-c4be-417f-b928-ecae3fd62226)

**Comment by ornech** [comment]
@ManRiick Les 2 champs serves à confirmer le mot de passe. Si l'utilisateur fait une erreur sur le première saisie et que l'on valide automatiquement le 2eme champs, on risque d'avoir beaucoup de retours "Mon mot de passe ne marche pas". La logique est que l'on à 2 champs qui se contrôle l'un et l'autre par grace à un petit script. De cette manière on lève le doute.

**Comment by ManRiick** [comment]
![image](https://github.com/ornech/gestion_stage/assets/154450104/1b0e4afd-ef6b-48fe-a944-911a9286db73)
![image](https://github.com/ornech/gestion_stage/assets/154450104/9bfe4b1b-868a-411b-b01b-219533dfe69b)

je disais faire une truc comme ca

**Comment by ornech** [comment]
@ManRiick
Si je comprend bien, l'idée est de ne pas demander de mot de passe à la création d'un utilisateur, mais que le mot de passe par défaut soit "achanger" ? Bien évidement j'imagine que l'utilisateur devra changer de mot de passe à la première connexion .
Ca peut-être une idée à creuser.

**Comment by Logan-Gaillard** [comment]
Bonjour, voici mon formulaire : 
Lorsqu'il est rempli
![image](https://github.com/ornech/gestion_stage/assets/35261972/86b0c943-532a-4102-9f54-0f7eec0f6992)

Lorsqu'il est vide
![image](https://github.com/ornech/gestion_stage/assets/35261972/4216652b-1c3e-40e7-bbdf-0b6f99e8a01e)

J'ai juste à faire une adaptation avec le statut de professeur.


De plus j'ai également une suggestion à faire pour permettre de créer des utilisateurs rapidement, c'est que lorsque le nom et le prénom est renseigné, un login se créer tout seul en suivant des conditions :
Par exemple, la première lettre du prénom puis les 7 première lettre du prénom.
Et on obtiendrai par exemple lgaillar.

**Comment by ornech** [comment]
@Logan-Gaillard . C'est pas mal. J'ai juste une petite observation. Est ce que l'on ne pourrait pas proposer un login automatiquement par exemple à partir du nom et du prénom ? Comme cela on reste dans la logique de limiter la saisie utilisateur au maximum.

**Comment by Logan-Gaillard** [comment]
C'est ce que j'avais proposé en bas de mon dernier message 😂
Je suis partant donc pour le réaliser

**Comment by ornech** [comment]
@Logan-Gaillard OK, on part la dessus. L'idée est de faire une proposition de login à partir du nom et prénom et que cette valeur soit préremplie dans le champs VALUE de ta balise INPUT. Comme cela si ça ne convient pas à l'utilisateur, libre à lui de le changer. Autre point pense qu'il existe des nom composé, et parfois des nom avec des espaces.

**Comment by Logan-Gaillard** [comment]
La fonctionnalité à été codée et fonctionne avec succès  :
[La vidéo](https://github.com/ornech/gestion_stage/assets/35261972/db1c5fb6-7c7a-4124-b650-6e98bdb25fc5)

**Comment by ornech** [comment]
C'est très bien. Quelques modifications mineures à apporter:
 * Changer "Elève" par "Etudiant"
 * Rajouter la spécialité (SLAM ou SISR) -> Nom du champ "spe" . On modifira le modèle et le controlleur demain pour que 
 * On discutera aussi de la fonctionnalité qu'a codé Astrik

**Comment by Logan-Gaillard** [comment]
Nous pensons avoir terminé avec vue_profil_create_user.

Voici ce que Astrick nous avons fait :
![image](https://github.com/ornech/gestion_stage/assets/35261972/d46f0dba-364b-4c60-be8b-08f5f440d791)
![image](https://github.com/ornech/gestion_stage/assets/35261972/957da062-01ec-42b9-96c9-004db32b900f)

Qu'en pensez vous ?
(La branche à été mit à jour avec tout ces nouvelles fonctionnalité)

**Comment by Logan-Gaillard** [comment]
Je continue sur cette branche pour la modification du modèle et controller
