### ISSUE TITLE
[BUG] Gestion des classes

### ISSUE THREAD

**Issue by ornech** [ornech/gestion_stage#427]
La mise à jour de la base de données avec les données de production ne permettent plus de voir le nombre d'étudiants dans une classe depuis la vue gestion de classe.

Pour que l'étudiant soit comptabilisé, il faut revalider le formulaire classe depuis sont profil.

**Comment by Logan-Gaillard** [comment]
Ceci n'est pas vraiment un bug, mais plutôt une problématique de moment d'exécution du controlleur.

Car en ce moment, le controlleur verif_etudiant.php qui s'occupe des attributions de classes est appelé lorsque nous faisons un forearch des étudiants lors de la connection d'un professeur ou bien lorsque la classe de l'étudiant à été changé dans son profil.
