### ISSUE TITLE
[ENTREPRISE] ajout manuel

### ISSUE THREAD

**Issue by ornech** [ornech/gestion_stage#463]
L'ajout manuel d'une entreprise n'est pas assez sécurisé:
1) L'enregistrement est réalisé dans la DB dès que tous les champs sont remplis
2) L'enregistrement dans la base de données n'a pas l'air complet (à vérifier)
3) Il manque une demande de validation a réaliser par le professeur assigné
4) L'entreprise ajoutée ne doit être visible tant qu'elle n'a pas été validée

**Comment by Logan-Gaillard** [comment]
On va commenter tout ce qui est ajout manuelle de l'entreprise
