### ISSUE TITLE
génération de la convention de stage automatiquement

### ISSUE THREAD

**Issue by patricedenis** [ornech/gestion_stage#50]
Il serait interessant de pouvoir générer automatiquement une convention de stage pour les candidats aux stages.
Peut-être avec un formulaire :
- pour remplir automatiquement les informations personnelles des candidats
- pour faire remplir les informations des entreprises qui sont prêtes à signer avec un candidat
- procédure de signature numérique automatique (en bonus)
- autres idées les bienvenues, merci de poursuivre sur le développement de cette idée dans le fil de discussion associé.
-

**Comment by ornech** [comment]
> Il serait interessant de pouvoir générer automatiquement une convention de stage pour les candidats aux stages.
> Peut-être avec un formulaire :
> - pour remplir automatiquement les informations personnelles des candidats
> - pour faire remplir les informations des entreprises qui sont prêtes à signer avec un candidat
> - procédure de signature numérique automatique (en bonus)
> - autres idées les bienvenues, merci de poursuivre sur le développement de cette idée dans le fil de discussion associé.
> - 

Remplacé par l'issue #
