### ISSUE TITLE
[CONTACT] ajouter

### ISSUE THREAD

**Issue by ornech** [ornech/gestion_stage#76]
1) Créer la méthode "create()"
2) Créer la vue "contact_create.php"

Notes:
Récupérer l'idEntreprise dans un champ HIDDEN HTML
Pour Created_UserID -> Récupérer la données dans $_SESSION
Pour Created_date -> faire Created_date=NOW() dans la requête SQL

**Comment by Logan-Gaillard** [comment]
Juste une petite question.

Dans la vue de la bdd nommé contact_employe du coup il y a UserID et Created_User(Le username)
On avait dit que ce n'était pas cohérent et donc je voulait savoir si je le rempli tout de même ou je les laisse NULL ?

Puis pourra récupérer le nom on fera des jointures dans la requête SQL.
